version: '3.8'

services:
  pokerouge-client:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: pokerouge-client
    ports:
      - "8000:8000"
    environment:
      VITE_BYPASS_LOGIN: "-1"
      VITE_BYPASS_TUTORIAL: "0"
      VITE_SERVER_URL: "http://localhost:8001"
      VITE_DISCORD_CLIENT_ID: "1248062921129459756"
      VITE_GOOGLE_CLIENT_ID: "955345393540-2k6lfftf0fdnb0krqmpthjnqavfvvf73.apps.googleusercontent.com"
      VITE_I18N_DEBUG: "0"
