apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Release.Name }}-{{ .Values.back.image }} 
  labels:
    app: {{ .Release.Name }}-{{ .Values.back.image }}
spec:
  replicas: {{ .Values.back.replica }}
  selector:
    matchLabels:
      app: {{ .Release.Name }}-{{ .Values.back.image }}
  template:
    metadata:
      labels:
        app: {{ .Release.Name }}-{{ .Values.back.image }}
    spec:
      restartPolicy: Always
      containers:
        - name: {{ .Values.back.image }} 
          image: {{ .Values.back.repo }}/{{ .Values.back.image }}:{{ .Values.back.tag }}
          env:
            - name: dbaddr
              value: "{{ .Release.Name }}-{{ .Values.db.image }}-svc"
            - name: dbuser
              value: "{{ .Values.back.env.dbuser  }}"
            - name: dbname
              value: "{{ .Values.back.env.dbname }}"
            - name: gameurl
              value: "http://{{ .Release.Name }}-{{ .Values.front.image }}-svc:{{ .Values.front.port }}"
            - name: callbackurl
              value: "http://{{ .Release.Name }}-{{ .Values.back.image }}-svc:{{ .Values.back.port }}"
            - name: dbpass
              valueFrom:
                secretKeyRef:
                  name: {{ .Release.Name }}-secret-mysql
                  key: password
          ports:
            - containerPort: 8001
              protocol: TCP
